// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgrwypqeawjmuxaxjiem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFncnd5cHFlYXdqbXV4YXhqaWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTAzNjgsImV4cCI6MjA1OTkyNjM2OH0.aIhE6vFoJJed-kzEvWOiKiJ021SswiaHY6GJhHpFUC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);